### ISSUE TITLE
DT Overlay Functionality not available after reboot

### ISSUE THREAD

**Issue by greenbreakfast** [OnionIoT/OpenWRT-Packages#100]
# What package does this bug affect?

`onion-dt-overlay-sw-spi` and `onion-dt-overlay-w1-gpio` in the `openwrt-23.05` branch

~~And most likely in `openwrt-22.03` branch as well~~
EDIT: tested on openwrt-22.03 based firmware and did not find the same issue. See [comment below](https://github.com/OnionIoT/OpenWRT-Packages/issues/100#issuecomment-2163580566) for details.

# **Describe the bug**

The functionality added by installing Device Tree Overlay packages is only available until the device is powered off or rebooted. 
Once the device reboots, the DT overlay seems to still be in place, but the functionality is not available. That is the additional software SPI bus and the one-wire master are not available.

# **To Reproduce**

*Used the [OnionIoT/omega2-fw-tester](https://github.com/OnionIoT/omega2-fw-tester) to test this quickly*

1. Flash the latest [`onion_omega2p-23.05.3-20240610.bin` firmware](http://repo.onioniot.com.s3.amazonaws.com/omega2-dev/images/openwrt-23.05/onion_omega2p-23.05.3-20240610.bin) to the device
2. Setup wifi or otherwise connect the device to the internet
3. On connected computer, run `pytest -v test_device.py --json-config test_cases/400_opkg_update.json test_cases/600_dt_overlay.json`, observe all tests pass
  <img width="1051" alt="Screenshot 2024-06-10 at 3 52 00 PM" src="https://github.com/OnionIoT/OpenWRT-Packages/assets/6757320/a4b26408-8618-426b-aa4e-64517a0b75c3">

4. Reboot the Omega2 device
5. On connected computer, run `pytest -v test_device.py --json-config test_cases/600_dt_overlay.json`, observe the tests that check functionality fail:
  <img width="1050" alt="Screenshot 2024-06-10 at 4 02 01 PM" src="https://github.com/OnionIoT/OpenWRT-Packages/assets/6757320/c2899d71-b36b-4f8c-9d6b-993576232eb9">

  

# **Expected behavior**

Expecting Software SPI and One-Wire Master to be available and work properly after a reboot or power off

# **Screenshots or Console output**

After initial installation of the dt overlay packages (step 3 above), tested manually on command line and both SW SPI and One-Wire worked. Could even read temperature data from a connected sensor:
<img width="647" alt="Screenshot 2024-06-10 at 3 51 50 PM" src="https://github.com/OnionIoT/OpenWRT-Packages/assets/6757320/b7f7fefb-930f-4ffb-bacd-04db80b450f9">

After rebooting the device (step 4 above), tested manually on command line again. No SW SPI device available, not one-wire master device available:
<img width="570" alt="image" src="https://github.com/OnionIoT/OpenWRT-Packages/assets/6757320/1a543eff-cede-40e8-861e-8cf79d63622f">
 

# **Version Info (please complete the following information):**
 - Firmware version: 23.05.3-20240610
 - Package name: `onion-dt-overlay-sw-spi` and `onion-dt-overlay-w1-gpio`
 - Package Version: `1.0-5`
 - Repo branch (if applicable) `openwrt-23.05` branch

**Comment by greenbreakfast** [comment]
Tested on **22.03.5**-20240517 firmware and did not have the same issue. So **this issue is only present on the 23.05.3 firmware!**

After fresh fw install:
<img width="1051" alt="image" src="https://github.com/OnionIoT/OpenWRT-Packages/assets/6757320/5b0818c9-ec3d-42ae-9d69-e34760b425c4">

After reboot:
<img width="1052" alt="image" src="https://github.com/OnionIoT/OpenWRT-Packages/assets/6757320/831e36e6-5c6d-408e-a60f-26d21cbf2105">

**Comment by YevheniiOnishchenkoLemberg** [comment]
Fixed in PR "Fix dt-overlay patch #35". Results below are for initial boot and after pressing the reset button. The failed "boot" test case indicated actual reset was happening:


![Image](https://github.com/OnionIoT/OpenWRT-Packages/assets/165658242/44107206-38ed-4add-bfb2-c5951c830d92)





![Image](https://github.com/OnionIoT/OpenWRT-Packages/assets/165658242/a4aa0073-7bdb-4f81-bfb2-2b0f7b4986c2)

**Comment by greenbreakfast** [comment]
Confirming this issue is resolved in the [`23.05.3-20240724` release](https://github.com/OnionIoT/OpenWRT-Packages/releases/tag/23.05.3-20240724).

**Successfully** tested on [`23.05.3-20240724` firmware](http://repo.onioniot.com.s3.amazonaws.com/omega2/images/openwrt-23.05/onion_omega2p-23.05.3-20240724.bin) from [`23.05.3-20240724` release](https://github.com/OnionIoT/OpenWRT-Packages/releases/tag/23.05.3-20240724)


Followed [test procedure from original post](https://github.com/OnionIoT/OpenWRT-Packages/issues/100#issue-2344741904)
After fresh fw install, dt-overlay installation and functionality checks pass:
<img width="998" alt="Screenshot 2024-07-26 at 11 01 52 AM" src="https://github.com/user-attachments/assets/a1da123f-a439-4568-b683-405099c9c3a3">


After reboot, dt-overlay functionality checks pass:
<img width="993" alt="Screenshot 2024-07-26 at 11 06 41 AM" src="https://github.com/user-attachments/assets/f8af2c52-60b5-4036-908a-3e98b73b0023">

Also tested one-wire device after reboot, works as expected. ~~Just noticed a few ghost one-wire slave devices, but that can be investigated at a later date:~~
EDIT: no ghost devices are detected if one-wire master pin is not left floating
<img width="570" alt="image" src="https://github.com/user-attachments/assets/13f312a8-c504-4b17-9b6c-44cedd0f0589">
