### ISSUE TITLE
Getting Error: at building time of node with libv8

### ISSUE THREAD

**Issue by anindya1989** [OnionIoT/OpenWRT-Packages#2]
# Getting Error: at building time of node with libv8
install -d -m0755 /home/test/work_XX_Demo/openwrt/build_dir/target-mipsel_mips32_glibc-2.19/node/ipkg-prj_mips/libv8/usr/lib
cp -fpR   /home/test/work_XX_Demo/openwrt/build_dir/target-mipsel_mips32_glibc-2.19/node/v8/lib/libv8.so /home/test/work_XX_Demo/openwrt/build_dir/target-mipsel_mips32_glibc-2.19/node/ipkg-prj_mips/libv8/usr/lib/
find /home/test/work_XX_Demo/openwrt/build_dir/target-mipsel_mips32_glibc-2.19/node/ipkg-prj_mips/libv8 -name 'CVS' -o -name '.svn' -o -name '.#*' -o -name '*~'| xargs -r rm -rf
Package libv8 is missing dependencies for the following libraries:
libc.so.0
libm.so.0

**Comment by mh1412** [comment]
We updated node to version 4.3.1. libv8 is no longer required as a stand along library.
