### ISSUE TITLE
SpiDev Data In not working

### ISSUE THREAD

**Issue by makermelissa** [OnionIoT/OpenWRT-Packages#34]
When using SpiDev and using any of the xfer functions, the result I get back from the MISO pin is always 0. I have verified with a logic analyzer that it is in fact a different value and it works fine on other boards. MOSI also works fine. The issue also happens when interacting directly with ioctl, so python3-spidev is likely not the issue and it may be a kernel level issue.

**Comment by greenbreakfast** [comment]
Only half-duplex SPI transactions are supported. You won't get valid data on a full-duplex transaction. More details here: https://github.com/OnionIoT/python-spidev#more-details-on-use-with-the-omega2

For half-duplex transmissions, try using the xfer3 function in our python-spidev package. More details here: https://github.com/OnionIoT/python-spidev#half-duplex-transmissions
