### ISSUE TITLE
wifimanager git repo not found

### ISSUE THREAD

**Issue by phatina** [OnionIoT/OpenWRT-Packages#5]
Building LEDE with Omega2 feeds fails to compile:

```
Checking out files from the git repository...
Cloning into 'wifimanager'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by greenbreakfast** [comment]
The wifimanager package is deprecated. Please use `wifi-warp-core` instead.

**Comment by eflukx** [comment]
Please mark broken packages as "broken" and/or "deprecated" 
See #15, #13

**Comment by greenbreakfast** [comment]
Ok, deprecated packages moved to `deprecated` directory, this includes #13 and #15.
Please confirm your build is ok
