### ISSUE TITLE
P44-Ledchain

### ISSUE THREAD

**Issue by DocHardinger** [OnionIoT/OpenWRT-Packages#52]
# Context

OpenWrt 22.03.
http://repo.onioniot.com/omega2/images/openwrt-22.03/

# Motivation

Possibility of controlling WS Leds would be a nice feature. As in 18.06. p44-ledchain is working.

# Description

Add a patch for p44-ledchain? to use it on OpenWrt 22.03.

# Alternatives Considered

Using other methods to control WS Leds over hardware pwm.

# Reference to existing IPK package file?

https://github.com/plan44/plan44-feed/tree/master/p44-ledchain

**Comment by greenbreakfast** [comment]
Loving the double feedback 👍 

Similar to #51, this depends on customization of the kernel. 
We'll add this in once we're done with the infrastructure setup in https://github.com/OnionIoT/openwrt-imagebuilder-wrapper/issues/4

**Comment by greenbreakfast** [comment]
@jempatel please tackle this next. 
Let me know if you think this would be better as a patch to openwrt-imagebuilder-wrapper or if we can do it with another method

**Comment by jempatel** [comment]
@greenbreakfast Yes, This would need a patch as it is a kernel package, It can be used as is. We can not use them separately because it needs to be built with all kernel modules and it would change the hash of the kernel.

If kernel module source code would have been in a separate repo, we would only need a Makefile to patch.

**Comment by greenbreakfast** [comment]
* [x] Add patch to openwrt-buildsystem-wrapper to support kernel module -> added in [Release 20231002-00](https://github.com/OnionIoT/openwrt-buildsystem-wrapper/releases/tag/20231002-00)
* [x] build new beta firmware that's based on the newly compiled kernel hash -> 22.03.5-20221003
* [ ] test latest firmware with compatible LED hardware to confirm proper operation

**Comment by TT-E1NFACH** [comment]
Tested it with an Omega2 Pro, running custom build firmware 22.03.05, using PWM CH0 with an WS2815 led strip (8 leds).
Works fine! 

What ive done:

```
opkg install kmod-p44-ledchain
insmod p44-ledchain ledchain0=0,8,5
omega2-ctrl gpiomux set pwm0 pwm
echo -en '\xFF\x00\x00\xFF\x00\x00' >/dev/ledchain0
```

Was just a quick test, not doing any stress test or so. But seems to work fine without flickering or anything.

**Comment by greenbreakfast** [comment]
Thanks for the confirmation @TT-E1NFACH 

Added brief documentation to the new beta firmware documentation site: https://documentation.onioniot.com/hardware-interfaces/ledchain

More news about this soon :)
