### ISSUE TITLE
Using hardware pwm the easy way (Bring back onion tool)

### ISSUE THREAD

**Issue by TT-E1NFACH** [OnionIoT/OpenWRT-Packages#61]
# Context

OpenWrt 22.03

# Motivation

In old version of your Onion Firmware (0.3.3) it was possible to use `onion pwm <CHANNEL> <DUTY CYCLE> <FREQUENCY>`. This was an easy way to use PWM.

# Description

Bring the old onion tool back to OpenWrt 22.03 to make use of PWM and other stuff easier.

# Alternatives Considered

Writing a python module which uses the console commands to make use of pwm easier

# Additional Resources

https://docs.onion.io/omega2-docs/generating-pwm-signals.html

**Comment by greenbreakfast** [comment]
@TT-E1NFACH agreed, the `onion pwm` command is much friendlier. 
I think a simple shell script (like the existing onion utility) will serve the purpose of making pwm easier to use. Writing it in python is fine but it's definitely not as lightweight.

Which other parts of the `onion` utility do you find useful?

**Comment by TT-E1NFACH** [comment]
If at all only the timeusage function would be another useful function for us.

**Comment by greenbreakfast** [comment]
@TT-E1NFACH The onion script is now available for the beta firmware! 
It's part of a new `omega2-script` package that's not included in the firmware but can be installed. For now it only supports  the `pwm` and `time` commands.

Check out the updated documentation here: https://github.com/OnionIoT/OpenWRT-Packages/blob/openwrt-22.03/technical-doc.md#enabling-pwm-pins

I'm gonna close this issue but feel free to reopen it if you have any issues.
