### ISSUE TITLE
Default WiFi AP ssid is different from cli device name

### ISSUE THREAD

**Issue by mh1412** [OnionIoT/OpenWRT-Packages#79]
# What package does this bug affect?

omega2-base

# **Describe the bug**

Default wifi AP ssid is 1 up from CLI device name

# **To Reproduce**

1. Boot up Omega2
2. Connect to Omega2 cli over UART
3. Observe the default host name in CLI `root@Omega-xxxx`
4. Observe the wifi-iface ssid option in /etc/config/wireless
7. See that the default wifi AP ssid is 1 up from CLI device name

# **Expected behavior**
The 4 digit code at the end of AP SSID should match with the CLI host name which should also match with the MAC address sticker on device.

# **Screenshots or Console output**
<img width="180" alt="image" src="https://github.com/OnionIoT/OpenWRT-Packages/assets/1589034/db27e163-bb26-4159-b037-d2e0411bea29">
<img width="278" alt="image" src="https://github.com/OnionIoT/OpenWRT-Packages/assets/1589034/c4bee9a3-1495-4923-a1d7-89eba5373428">

# **Version Info (please complete the following information):**
 - Firmware version: [22.03.5 b20231109]
 - Package name [omega2-base]
 - Package Version [22.03.5-20231109]
 - Repo branch (if applicable) [openwrt-22.03]

# **Additional context**
N/A

**Comment by greenbreakfast** [comment]
✅ Merged in the changes and confirmed the hostname and wifi ap ssid are now based on the wlan0 mac address and match each other.

---

With older beta firmware:
```
root@Omega-f195:/# opkg list-installed | grep omega2-base
omega2-base - 22.03.5-20231109
```
```
root@Omega-f195:/# uci show wireless.default_radio0.ssid
wireless.default_radio0.ssid='Omega-f196'
```

❌ hostname is based on wlan0 mac address but has lowercase `f`
❌ wifi AP name is based on eth0 mac address and has lowercase `f`

---

After installing latest beta firmware with this change:
```
root@Omega-F195:/# opkg list-installed | grep omega2-base
omega2-base - 22.03.5-20240122
```
```
root@Omega-F195:/# uci show wireless.default_radio0.ssid
wireless.default_radio0.ssid='Omega-F195'
```

✅ hostname based on wlan0 mac addr and has capitalized `F`
✅ wifi AP name matches hostname (based on wlan0 mac addr and has capitalized `F`)

**Comment by greenbreakfast** [comment]
whoops, I marked this issue as closed and it pulled the ticket into the completed column. 
Is that correct as per our process @amsiotdeveloper
