### ISSUE TITLE
Migration to OpenWRT 23.05.3 - Major Release - Part 1

### ISSUE THREAD

**Issue by amsiotdeveloper** [OnionIoT/OpenWRT-Packages#85]
# Context

Specify which branch of this repo or firmware version you're referring to

new openwrt-23.05 branch

# Motivation

Why are we doing this? What use cases does it support? What problems does it solve? What is the expected outcome?

The purpose of this scope is to update our firmware to OpenWRT 23.05.3

This scope is working with the new OpenWRT release so it has a major impact on all 3 value tracks

Development
Deployment
Production

- The goal is to compile and test packages and firmware based on the new OpenWRT release that’s built with the vanilla SDK and Image Builder released by OpenWRT

Vanilla = unmodified

This is an intermediate step to make the transition smoother. We can identify major issues without the additional variables introduced by using our own customized SDK and Image Builder

# Description
It should be reasonably clear how the improvement would be implemented.

1. Create new branch for the release in the OnionIoT/OpenWRT-Packages repo
    1. The branch should be based on the previous release and should be named to match the OpenWRT release name, for example `openwrt-22.03` for OpenWRT 22.03
2. Make changes to support the new release
    1. Update a local copy of the openwrt-sdk-wrapper repo to:
        1. Use the SDK released by OpenWRT for the target release
        2. Use the new branch of the OpenWRT-Packages repo as the package feed
    2. Update a local copy of the openwrt-imagebuilder-wrapper repo  to:
        1. Use the Image Builder released by OpenWRT for the target release
        2. Update omega2 packages repo URL - point to a local location
    3. In the OpenWRT-Packages repo, in the new branch
        1. update the `omega2-base` package version to match the new OpenWRT release
        2. update the `omega2-base` package release number to match the date
3. Build the packages and firmware based on the new release
    - Debug compilation issues as needed

###  2. What does the task owner require for a successful completion of the ticket?
    i.e. sample code, drawings, documents etc.

1. Implement the mentioned steps.
2. Identify and address any issues that arise.
3. Implement the tests in the checklist below and provide test results accordingly. 

# Additional Resources

Provide hyperlinks for helpful and related information.

OnionIoT/OpenWRT-Packages

OnionIoT/openwrt-sdk-wrapper

OnionIoT/openwrt-imagebuilder-wrapper

# **The Workflow:**
- [x] Subtask 1: Execute the mentioned steps to perform Part 1 of the migration.
- [ ] Subtask 2: Execute the test process in Ticket #86  
- [ ] Subtask 3: Review test results for approval to proceed with Part 2.

# Deliverables

* New `openwrt-23.05` branch in OnionIoT/openwrt-packages repo that is configured to build:
  * the packages in the OnionIoT/openwrt-packages repo (using the openwrt-23.05 SDK)
  * firmware based on the openwrt-23.05.3 release
* Successful compilation of packages in `openwrt-23.05` branch in OnionIoT/openwrt-packages repo by the OnionIoT/openwrt-sdk-wrapper
* Successful compilation of firmware by the OnionIoT/openwrt-imagebuilder-wrapper

**Comment by greenbreakfast** [comment]
@amsiotdeveloper looks good!

Wanted to add an **implementation-related note**:
moving forward, we'll try to make OnionIoT/openwrt-packages the only repo that changes with new openwrt releases, while OnionIoT/openwrt-sdk-wrapper and OnionIoT/openwrt-imagebuilder-wrapper stay unchanged.

To facilitate that, we've moved the sdk and image builder profile files into the OnionIoT/openwrt-packages repo.

Work to update the CD system to implement this is starting this week

EDIT: this work is complete. The `sdk-profile` and `imagebuilder-profile` config files in the OnionIoT/openwrt-packages repo are used by the CD system to build packages and firmware.

**Comment by greenbreakfast** [comment]
Released packages and firmware based on OpenWRT 23.05.3 and built with the vanilla OpenWRT SDK and Image Builder
See release here: https://github.com/OnionIoT/OpenWRT-Packages/releases/tag/23.05.3-20240531

Firmware available here: http://repo.onioniot.com/omega2/images/openwrt-23.05/
Onion packages available here: http://repo.onioniot.com/omega2/packages/openwrt-23.05.3/onion/

Closing this issue!
